default: &default
adapter: postgresql
encoding: unicode
host: <%= ENV["POSTGRES_HOST"] %>
port: <%= ENV["POSTGRES_PORT"] %>
username: <%= ENV["POSTGRES_USER"] %>
password: <%= ENV["POSTGRES_PASSWORD"] %>
pool: <%= ENV.fetch("POSTGRES_MAX_THREADS") { 5 } %>

development:
<<: *default
database: project_manager_development

test:
<<: *default
database: project_manager_test

production:
<<: *default
database: project_manager_production

